### ISSUE TITLE
5번째 heading 변경 의견

### ISSUE THREAD

**Issue by whyjp** [CppKorea/CodeOfConduct#1]
coc 순서  
신뢰할 수 있는 정보를 만들어주세요
가 5번째 헤딩에 오는 편이 어떨까요?
텍스트 내용
**"우리는 신뢰할 수 있는 정보를 만들고 공유합니다"** 로 이어지면 좋을것 같습니다 
하부 문장에서도 신뢰할 수 없는 정보라면 의견을 교환하고 보정한다는 내용이 있으니 서로 보완할수있고 신뢰할수 있는 정보로 만들어 나감도 의미 있을테니  신뢰할수 있는 정보가 아닌가 싶어서 선듯 포스팅을 못하는 경우도 있을 수 있을것 같습니다

**Comment by GiyeonBang** [comment]
안녕하세요. Heading 순서의 변경에 대한 의견을 주셔서 감사합니다.
CoC TF에서 원안 구성시 Heading의 순서를 CoC 작성 당시에 “구성원의 존중”, “다양성 포용”, “커뮤니티의 대화 예절/매너”, “정보의 신뢰성”의 순서로 구성하였습니다. 새로운 항목을 추가할 때 제안을 함께 고려하겠습니다.
@whyjp 님의 의견을 반영해 더 좋은 CoC를 만들도록 하겠습니다. 감사합니다.
