### ISSUE TITLE
동어 반복 표현

### ISSUE THREAD

**Issue by conr2d** [CppKorea/CodeOfConduct#2]
https://github.com/CppKorea/CodeOfConduct/blob/78cc9477623469f43980ae22c3417b6a46aabfb5/README.md#L12

동어반복적인 느낌이 있는데 "의사소통 예의를" 또는 "커뮤니케이션 매너를" 둘 중 하나를 고르려다 미완성된 문장이 삽입된 것은 아닌가요?

**Comment by utilForever** [comment]
오타를 발견해주셔서 감사합니다. 수정하겠습니다.
